definitions:
  models.Client:
    properties:
      fullname:
        type: string
      id:
        type: string
      phone:
        type: string
    type: object
  models.CreateClientBody:
    properties:
      fullname:
        type: string
      phone:
        type: string
    type: object
  models.CreateDriverBody:
    properties:
      fullname:
        type: string
      phone:
        type: string
    type: object
  models.Driver:
    properties:
      fullname:
        type: string
      id:
        type: string
      phone:
        type: string
    type: object
  models.Error:
    properties:
      message:
        type: string
    type: object
  models.StandardErrorModel:
    properties:
      error:
        $ref: '#/definitions/models.Error'
    type: object
info:
  contact: {}
paths:
  /v1/clients/:
    post:
      consumes:
      - application/json
      description: This API for creating a new client
      parameters:
      - description: clientCreateRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateClientBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: CreateClient
      tags:
      - client
  /v1/clients/{id}:
    delete:
      consumes:
      - application/json
      description: This API for deleting client
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: DeleteClient
      tags:
      - client
    get:
      consumes:
      - application/json
      description: This API for getting client detail
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetClient
      tags:
      - client
    put:
      consumes:
      - application/json
      description: This API for updating client
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: clientUpdateRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateClientBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: UpdateClient
      tags:
      - client
  /v1/drivers/:
    post:
      consumes:
      - application/json
      description: This API for creating a new driver
      parameters:
      - description: driverCreateRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateDriverBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: CreateDriver
      tags:
      - driver
  /v1/drivers/{id}:
    delete:
      consumes:
      - application/json
      description: This API for deleting driver
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: DeleteDriver
      tags:
      - driver
    get:
      consumes:
      - application/json
      description: This API for getting driver detail
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: GetDriver
      tags:
      - driver
    put:
      consumes:
      - application/json
      description: This API for updating driver
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: driverUpdateRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateDriverBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Driver'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StandardErrorModel'
      summary: UpdateDriver
      tags:
      - driver
swagger: "2.0"
